### ISSUE TITLE
Support configure a user-defined API domain name

### ISSUE THREAD

**Issue by RogerYK** [carlrobertoh/CodeGPT#118]
When using OpenAI, I'll create a reverse proxy server for the following reasons.
1. Bypass the firewall and OpenAI region restrictions
2. Use [azure-openai-proxy](https://github.com/stulzq/azure-openai-proxy) to use the OpenAI service in azure
3. Insert the api key into the server instead of configuring it on the client side, so that it can be easily shared to multiple people.

this is an uncomplicated but useful function, hope can be supported

**Comment by carlrobertoh** [comment]
Hi, using a custom  service should allow you to use reverse proxy server:

<img width="630" alt="Screenshot 2023-06-17 at 14 45 26" src="https://github.com/carlrobertoh/CodeGPT/assets/15891408/08bd04fb-51bb-4404-a356-57c30c9aa8f6">

**Comment by RogerYK** [comment]
I actually overlooked this place, I tried it out and it looks well. Thank you 😊

**Comment by carlrobertoh** [comment]
Glad you got it worked out. Closing the issue.

**Comment by emailtoakash** [comment]
Where is this custom service? I was trying but I cannot find it 
I would like to also use my own open AI service, and it uses a Token instead of key. can you please check? also how can i find the curl request what the plugin makes? 

![image](https://github.com/carlrobertoh/CodeGPT/assets/6198894/49def5d8-6c3c-41c4-99cf-7857ae9be05d)
