### ISSUE TITLE
Dont steal focus when prompt response is completed

### ISSUE THREAD

**Issue by OrbiterToad** [carlrobertoh/CodeGPT#126]
When Prompt response is completed, the CodeGPT 'ask' input field automatically requests the cursor focus.

**To reproduce**:
1. Ask prompt
2. Manually switch focus to Editor window
3. Wait until prompt complete

**Expected**: 
- Should NOT request focus if editor window or other ui component is currently in focus.
- Should only request focus if the CodeGPT plugin is currently in focus

**Comment by carlrobertoh** [comment]
Hi @OrbiterToad,

Setting the focus on the text area's input after the completion was done on purpose. However, stealing the focus from other inputs is definitely a bug. 

Unfortunately, the plugin hasn't been tested on Linux nor Windows, so there might be other things that I missed.

FYI, I really appreciate that you removed the rating from the marketplace and reported the bug here. I will try to fix the issue as soon as possible.

Best regards,
Carl

**Comment by carlrobertoh** [comment]
Hi,

Please try upgrading to the latest version to see if the problem still exists.
https://plugins.jetbrains.com/plugin/21056-codegpt/versions/stable/348931

Thank you!
