### ISSUE TITLE
There is absolutely no output; only a blinking cursor.

### ISSUE THREAD

**Issue by Marcel176** [carlrobertoh/CodeGPT#132]
There is absolutely no output; only a blinking cursor.

![image](https://github.com/carlrobertoh/CodeGPT/assets/35179083/b959289c-c515-47c4-9659-e60ec58310f0)

**Comment by carlrobertoh** [comment]
Hi, do you see any error logs in the IDE's console?

OpenAI API seems to be overloaded at the moment. In the meantime, you could switch to a previous version and see if the problem still persists: https://plugins.jetbrains.com/plugin/21056-codegpt/versions/stable/336355.

**Comment by petrovo-as** [comment]
Hi,
I have the same problem since version 2.0.0. The reload and delete response icons cannot be clicked.

Version 1.10.8 works perfectly.
1.11.0 is not color-highlighted PHP code.

I'm using OS: Linux, PhpStorm 2023.1.2 Build #PS-231.9011.38
  JDK: 17.0.6; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.

I don't see any error if I run PhpStorm in the console.
Neither [
OkHttp https://api.openai.com/...] INFO ee.carlrobert.openai.client.completion.CompletionEventSourceListener - Request opened.
[OkHttp https://api.openai.com/...] INFO ee.carlrobert.openai.client.completion.CompletionEventSourceListener - Request closed.

**Comment by carlrobertoh** [comment]
I'm still unable to reproduce the blinking cursor bug (tried 3 different OS using multiple IDEs) 🙄 

Apparently the PHP code doesn't get highlighted if the AI generated code is missing the `<?php` opening tag.
Either I need to write a custom logic for it or tweak the system prompt.

**Comment by Marcel176** [comment]
Hi Carlrobertoh/Codegpt,
I believe in my case you were right. There was no bug, but rather chat gpt
was slow. It is not obvious at the beginning, it looks weird, different
tabs may behave differently, but after I wait some time, it got back to
normal.

So it should be on the chat gpt end uless you can think of any overhead the
plugin may be adding to the process.

Thanks,
MŁ

**Comment by Marcel176** [comment]
Also in my case, as I remember, that behavior appeared just after I've
uploaded the update and restarted IDE, so it was a bad coincidence.
