### ISSUE TITLE
Mistake

### ISSUE THREAD

**Issue by Glosarik** [carlrobertoh/CodeGPT#135]
You exceeded your current quota, please check your plan and billing details.

**Comment by carlrobertoh** [comment]
Hi, please check your account usage - https://platform.openai.com/account/usage

**Comment by Glosarik** [comment]
And could it be done so as not to enter your api key? You have a cool plugin, but other plugins do not need to enter an api key

**Comment by carlrobertoh** [comment]
The plugin is built around OpenAI's API. ChatGPT and GPT-API are two different things each with their own pricing model. 

Would you mind sharing any plugins that don't require entering an API key?

Thank you!

**Comment by Glosarik** [comment]
ChatGPT GPT-4 (Bito) for example

**Comment by carlrobertoh** [comment]
With Bito, it appears that they are using their own internal api keys, which means that they are actually paying for your usage.
Even though they are promoting that they never store, view or copy your code, you can never be sure of that because the response you receive, is coming from their own service.
