### ISSUE TITLE
Auto read and generate files in current project!

### ISSUE THREAD

**Issue by Jarrodsz** [carlrobertoh/CodeGPT#141]
Nobody had thought of this idea before, so I'm posting it here. Either I must be a genius, or the rest of the people haven't thought of it yet.

Here's the proposal: within the plugin's features, add an option to write multiple files to the disk. This feature would be particularly useful when running locally on a development machine.

Here's an example prompt:
"Write me a 1-page React todo app in TypeScript. Write all components to /components."

When the plugin is enhanced, it should generate files with filenames as descriptions and save them to disk based on instructions or plugin settings that are relevant to the conversation. For instance, you could choose a specific output path from the browser or define a string variable with the output path, such as /my.nextjs.app.path/. The plugin should then write all the output files accordingly.

If this feature doesn't exist yet, I highly believe it is needed not just by me, but also by other developers. Let's work together to make this happen quickly!

I also have some additional improvement ideas for the plugin:

1. Ask to store files after they have been written and reviewed, or provide an option for "auto store" to save the generated files directly.

2. Allow users to set paths for output files, giving them more flexibility in organizing their codebase.

3. Add modes for generating or refactoring codebases. The plugin could load an existing application file tree, such as a Next.js, Remix, or PHP project, and read and refactor the files. As a bonus, consider implementing a drag-and-drop functionality in the plugin's UI to facilitate code refactoring.

4. Implement a conversion mode, where code can be converted from one language (X) to another (Y) based on the provided prompt.

Let's collaborate and make this brilliant addition to the open-source project a reality!

**Comment by carlrobertoh** [comment]
Hi @Jarrodsz 

Thank you for the feature requests!

Few comments on your provided suggestions:

> When the plugin is enhanced, it should generate files with filenames as descriptions and save them to disk based on instructions or plugin settings that are relevant to the conversation.

The AI doesn't have context related to the user's file system, meaning that including commands like 'Write all components to /dir' in the prompt shouldn't have any effect. Instead, this should be the plugin's responsibility, as you mentioned it in the first bullet point. However, with the recent [OpenAI functions](https://openai.com/blog/function-calling-and-other-api-updates) feature, I believe these two logics can be combined.

> Allow users to set paths for output files, giving them more flexibility in organizing their codebase.

I believe this should go together with the first request.

> Add modes for generating or refactoring codebases. The plugin could load an existing application file tree, such as a Next.js, Remix, or PHP project, and read and refactor the files. As a bonus, consider implementing a drag-and-drop functionality in the plugin's UI to facilitate code refactoring.

IMHO, this sounds rather dangerous and a waste of tokens because you can't really rely 100% on the AI to produce correct responses. Regarding the dnd feature, could you please provide me with more context about it??

> Implement a conversion mode, where code can be converted from one language (X) to another (Y) based on the provided prompt.

If I understood you correctly, then this should already be achievable. Simply highlight a code block and give it a prompt, for example, "Convert the selected code to JavaScript."

I actually like the idea of file generation, although I believe this should be done manually. For example having an action button for each code block which triggers a dialog or modal, allowing the user to specify the path and other configurations.

**Comment by carlrobertoh** [comment]
The described functionality can be achieved with agents. Closing this ticket since it is part of a larger implementation.

**Comment by iosifnicolae2** [comment]
> The described functionality can be achieved with agents. Closing this ticket since it is part of a larger implementation.

where can we find more information about the agents milestone?
