### ISSUE TITLE
Use free chat.openapi.com api key/session

### ISSUE THREAD

**Issue by Jarrodsz** [carlrobertoh/CodeGPT#142]
not sure if this is possible, but I wanted to drop it to you.

I have seen some of research projects that instrument usage of the free session on chat.openai.com 

This could be a useful extension of the plugin saving token costs.

**Comment by carlrobertoh** [comment]
It is possible via a reverse proxy, and in the early versions of the plugin, it was available. However, some users were banned because of it, so I completely removed the feature.

There is still an option to set up the proxy locally and use the custom host option in the plugin settings.
https://github.com/PawanOsman/ChatGPT
