### ISSUE TITLE
The plugin side panel doesn't open when select context actions for selected code

### ISSUE THREAD

**Issue by plagov** [carlrobertoh/CodeGPT#157]
Given, the plugin side panel is closed.
When I select a block of code and select the context menu for CodeGPT (Write Tests, Find Bugs, Optimize, etc):

![Screenshot 2023-07-09 at 17 03 05](https://github.com/carlrobertoh/CodeGPT/assets/16601852/46e9d2ed-bc61-4b1d-9da6-001905ba340f)

Then, the plugin doesn't open its side panel.

It probably should open.

Also, I would expect it to start a new chat for this action, but it continues the conversation in the last active chat.

**Comment by carlrobertoh** [comment]
- Fixed the bug related to opening the side panel.
- Added support for overriding the behaviour in the settings via `CodeGPT | Configuration | Open new tab on each action`

Made it configurable because few weeks ago I received a request NOT to open a new chat every time.

Available in the latest release.
