### ISSUE TITLE
Position in the right-click menu

### ISSUE THREAD

**Issue by rangzen** [carlrobertoh/CodeGPT#21]
Hello,

Is it possible to have a more "humble" position on the menu? All extensions place themselves at the top position, can we go to something more realistic with real day-to-day usage?
Not higher than copy/paste or the context action for example? Please...

In all cases, thank you for this plugin!

**Comment by carlrobertoh** [comment]
Hi @rangzen 

Yes we can, I will add this change to the next release.

Best regards

**Comment by carlrobertoh** [comment]
I hope this is more "humble" now 🙂 
<img width="463" alt="Screen Shot 2023-03-07 at 11 10 30" src="https://user-images.githubusercontent.com/15891408/223405916-7c81edc1-744d-4317-9b76-25e83c547ef7.png">

If you have good ideas for better wording then I'm all ears.

**Comment by carlrobertoh** [comment]
Hi

Thank you for the feedback and thinking along.

I totally agree with your statements, the actions menu and its position was just something that was left behind and didn't got much attention(until now). Also, I really like the UX/UI of the String Manipulation plugin's menu, so I'm thinking of doing something similar.

What do you think about this(perhaps with some "fancy" icons)?
<img width="675" alt="Screen Shot 2023-03-07 at 14 34 19" src="https://user-images.githubusercontent.com/15891408/223454164-9936fdb9-58ba-4c92-b67c-3230ff805a0c.png">
If you have some better wording for these actions then I'd love to hear about it 🙂 

> I would suggest to get ride of the "Ask ChatGPT" option since you will anyway go to the window tool.

Makes sense, however since the plugin lacks a proper way of clearing the current chat session, I've been using it as a workaround for now.

> By the way, with the new UI (beta), with a dark theme, the icon is strange:

I've been receiving some console errors related to icon size being bigger than required(512x512 vs 12x12), might be related, will check it out. Also in which IDE are you experiencing that?

Thanks again for the recommendations.

Best regards

**Comment by rangzen** [comment]
Very nice! I will try to think about it...
I would probably get rid of the sub-menu Predefined Prompts, add a separator, and put everything under. Until you have 20 of these, I think it is ok. Then you will probably need a submenu. It is a bit like for files and directory, or subjects in forums (for old folks), it is often better to wait a bit and do the ordering with a new level only when it is needed.

I am using Goland with the new UI
![image](https://user-images.githubusercontent.com/132700/223467829-0707558a-8c62-493f-8aa7-c9a286fe06fe.png)

**Comment by carlrobertoh** [comment]
Makes sense, thank you!
