### ISSUE TITLE
Count/Show all tokens used for the chat.

### ISSUE THREAD

**Issue by dz0** [carlrobertoh/CodeGPT#319]
### Describe the need of your request

I would like to see count of all tokens used for the chat historically.

Currently the chat shows only tokens, that are displayed in the chat. 
if  I regenerate or delete some parts.. their tokens "dissapear" form the sum..
Also I'd like to know if previous conversation is being sent together with each new message (in same chat)?

### Proposed solution

Keep track of all tokens sent/received in separate field.

### Additional context

because I started getting too big bills from openAI, though tokes count didn't indicate this would happen... :)

**Comment by carlrobertoh** [comment]
Unfortunately, displaying the count of all tokens used historically is not on the current roadmap.

> Also I'd like to know if previous conversation is being sent together with each new message (in same chat)?

Yes, the previous context is sent altogether with each new message. This is how conversational chatbots work.

To keep costs down, I would suggest using GPT-3.5 Turbo for most tasks and GPT-4 only when needed, as well as switching between new chats so that the context doesn't grow too large.
