### ISSUE TITLE
Login to You.com no longer works

### ISSUE THREAD

**Issue by melan** [carlrobertoh/CodeGPT#419]
### What happened?

They started demanding `dfp_telemetry_id` field as part of the password auth request to Stytch. It's a device fingerprint token, more [here](https://stytch.com/docs/fraud/guides/dfp-protected-auth/overview).

Without the field and the token it replies with 401 and fails the authentication with an error: `DFP telemetry ID not set`

### Steps to reproduce

Run Idea and maybe try to re-login.

### CodeGPT version

2.5.1

### Operating System

macOS

**Comment by msokolovsky-appulate** [comment]
![image](https://github.com/carlrobertoh/CodeGPT/assets/62114279/d4a531f1-575c-4e62-b5b5-150712cc7125)

**Comment by carlrobertoh** [comment]
The `dfp_telemetry_id` needs to be obtained from the You.com website and then must be passed into the Stytch request.

<img width="360" alt="Screenshot 2024-05-09 at 11 58 59" src="https://github.com/carlrobertoh/CodeGPT/assets/15891408/1bfb07a5-5f76-48ae-9213-0652deab352a">

However, since You.com doesn't provide an actual public API, I'm considering deleting this provider from CodeGPT entirely.

**Comment by 7zism3** [comment]
@carlrobertoh In the update "Jul 01, 2024 Version 2.8.2-241.1"
You.com support has been removed. I think why don't we try to fix it as suggested by @PhilKes . I and some users who have registered you pro will be really unhappy, if it is discontinued

**Comment by melan** [comment]
You.com is working on the actual API but currently it's locked to business customers only. So maybe one day they will be back
