### ISSUE TITLE
can't use groq

### ISSUE THREAD

**Issue by dss99911** [carlrobertoh/CodeGPT#511]
### What happened?

Connection failed.

Incorrect API key provided: $CUSTOM_***********_KEY. You can find your API key at
https://platform.openai.com/account/api-keys.

### Steps to reproduce

1. get api key from https://groq.com/

2. on codegpt setting,
- select custom openai service
- select 'Groq' on preset template
- input api key
- click test connection

the error below occurred
```
Connection failed.

Incorrect API key provided: $CUSTOM_***********_KEY. You can find your API key at
https://platform.openai.com/account/api-keys.
```

when I tested on curl below, it's working fine.
```
curl -X POST "https://api.groq.com/openai/v1/chat/completions" \
     -H "Authorization: Bearer $GROQ_API_KEY" \
     -H "Content-Type: application/json" \
     -d '{"messages": [{"role": "user", "content": "Explain the importance of fast language models"}], "model": "mixtral-8x7b-32768"}'
```

### CodeGPT version

2.6.3-241

### Operating System

macOS

**Comment by sisve** [comment]
The error message indicates that 1) you're talking to openai.com, and 2) you're sending the literal string $CUSTOM_SERVICE_API_KEY as your api-key.

Can you verify that you have configured an custom URL and api-key in your CodeGPT plugin settings?

**Comment by dss99911** [comment]
when I select 'Groq' on preset template.
it changes the URL to `https://api.groq.com/openai/v1/chat/completions` automatically. I used the url

**Comment by dss99911** [comment]
<img width="719" alt="image" src="https://github.com/carlrobertoh/CodeGPT/assets/13122274/870692e5-0b45-4f92-955c-7104b362e127">

**Comment by dss99911** [comment]
<img width="869" alt="image" src="https://github.com/carlrobertoh/CodeGPT/assets/13122274/2146efbe-20dd-4276-a988-1bd92979683a">

**Comment by carlrobertoh** [comment]
Did you apply the settings before testing the url? There's a small bug around that.

**Comment by dss99911** [comment]
the settings I mentioned above is applied before testing the connection

**Comment by reneleonhardt** [comment]
Same here since #476 has been merged, the wrong settings are being used for Custom OpenAI, depending on your application state.
If you switch presets, the default settings are being applied (Ollama has no code completions, tab is disabled).
If you enable code completions by hotkey or mouse, code completions become active with default settings for OpenAI (first FIM template autoselected), hence the incorrect `Incorrect API key provided` response for platform.openai.com (Ollama runs on localhost).
So the user settings are being overwritten sometimes with "default values" or empty values depending on `Preset template` change, `Enable code completions` change, `FIM template`... this feature is very flaky, I would suggest writing tests first for all supported services, models and FIM templates (success and errors like missing API key, unexpected API key, unexpected response). And especially changing user settings without the user knowing it, enabling code completions is only 1 flag in 1 location, but many more settings are changed/deleted/added in the background after this one action depending on the selected Preset and FIM.

**Comment by dss99911** [comment]
thanks for the solution. but, I couldn't understand the detail.
1. can it be fixed?
2. is there workaround before it's fixed?

**Comment by reneleonhardt** [comment]
Never open settings again before the next CodeGPT release 😅
Before closing settings, make sure to switch the Preset template first and check all settings to be correct.

**Comment by carlrobertoh** [comment]
@dss99911 

> is there workaround before it's fixed?

Delete `CodeGPT_CustomServiceSettings.xml` settings file from the options folder and restart your IDE.

https://intellij-support.jetbrains.com/hc/en-us/articles/206544519-Directories-used-by-the-IDE-to-store-settings-caches-plugins-and-logs

**Comment by PhilKes** [comment]
This is fixed by https://github.com/carlrobertoh/CodeGPT/pull/531
