### ISSUE TITLE
Ollama support from Intellij

### ISSUE THREAD

**Issue by moshere-cirm** [carlrobertoh/CodeGPT#528]
### What happened?

Trying to configure Ollama from intellij. Two problems:
1. UI is looking for API key
2. Once putting API key it failed in text connection

<img width="759" alt="image" src="https://github.com/carlrobertoh/CodeGPT/assets/148776732/23d2b798-0629-44f7-8d2b-a5b4c8e98c81">

### Steps to reproduce

Install codegpt on Intellij. Try to configure it with CustomOpenAI and Ollama. Put API key and test connection

### CodeGPT version

2.6.3-241

### Operating System

macOS

**Comment by PhilKes** [comment]
First of all Ollama doesn't offer the possibility to define an Api-Key, I think its only possible if you use a proxy (see https://github.com/ollama/ollama/issues/849)

The error messages seems to be coming from OpenAi instead of your Ollama Server, I noticed a bug that the `Test Connection`uses the stored settings instead of what is currently selected/entered in the settings UI. I have opened a PR fixing that (#531)
What happens if you click `Apply` and then hit `Test Connection`?

**Comment by Codemonk7777** [comment]
Anyone please help me to setup ollama in my intellj
