### ISSUE TITLE
Ability to copy and replace generated code snippets

### ISSUE THREAD

**Issue by carlrobertoh** [carlrobertoh/CodeGPT#56]

**Comment by carlrobertoh** [comment]
This sounds like a really lovely idea, however it seems like a huge change and requires some research. Also I'm not really familiar with the voice coding community and how they interact with the IDE. If you happen to have some source materials/links for reading, I would love to take a look.

**Comment by alvitawa** [comment]
This video has a nice demo: https://youtu.be/oB5TGMEhQp4?t=112

You can for example simply say 'control air' to press ctrl+a and saying 'say the quick brown fox jumped over the fence' will type out 'the quick brown fox jumped over the fence'. But for programming you usually can't just dictate what you want to write because it is not proper english. Meaning you have to spell things out: 'vest air red sit air bat looking each'  spells out 'variable' (although this example you could have also dictated).

So all that is really needed are keyboard shortcuts to be able to program by just selecting text and dictating code changes in natural language (code selection can be done fairly easily with vim commands). The nice thing about using chatgpt for voice coding is that dictating natural language is very easy using your voice. (using a mouse is not as easy for everyone)
Also chatgpt generally understands homophones so it can understand what you want to do even if not everything in the prompt is spelled correctly.

**Comment by alvitawa** [comment]
Here is at demo of the workflow I envision:

https://youtu.be/VZfBgaNA6wg

(with voice coding but also using the mouse when I have to)

**Comment by carlrobertoh** [comment]
@alvitawa 
As I understand there should be some kind of key mapping for each plugin's action that can be configured to talon commands?
For example, in IDE the "Build Project" is configured to "cmd-F9" keymap, in order for you to say "Build this project", you need to have a talon mapping for that specific keymap?

Thank you for the detailed video.

**Comment by carlrobertoh** [comment]
@dakotahNorth Yep, that was the idea! :)

**Comment by alvitawa** [comment]
@carlrobertoh 
Correct, talon can send any keymap based on user-configurable voice commands. But you can also just say the key map itself (which is what I do for most things). So ultimately all that is needed to use the plugin for hands-free voice editing are key mappings.
