### ISSUE TITLE
Very slow @file search freezes IDEA after each letter

### ISSUE THREAD

**Issue by scscgit** [carlrobertoh/CodeGPT#652]
### What happened?

After typing every letter after `@file:`, my entire IDEA window freezes again for over 20 seconds (i.e. loading is not asynchronous).

For reference, my project has over 2GB and over 20k files (most of which isn't source code). Obviously, full-text and file search in IDEA is always instant, as its indices are quite performant, so this plugin must be using a different API. I also didn't notice any settings for whitelisting or blacklisting directories from this search, so I assume it shares behavior with IDEA to only use modules from Project Settings.

![image](https://github.com/user-attachments/assets/61246208-0e02-44fb-be44-a9bb43de96fb)

### Steps to reproduce

Have a large project and type letters after `@file:`.

### CodeGPT version

2.9.0-241.1

### Operating System

Windows

**Comment by carlrobertoh** [comment]
Thanks for reporting! I'm not using the actual file search API per se, because I'm not sure what the ideal approach is. However, I've fixed the freeze issues for now (will be available in the next release), but the search might still take longer than the native file search that the IDE provides. I'll come back to this issue later.
