### ISSUE TITLE
Token Limits

### ISSUE THREAD

**Issue by chriskyndrid** [carlrobertoh/CodeGPT#68]
First, thanks for your efforts on this. CodeGPT is a useful tool for my workflow in CLion.

I realize the current limitation of the GPT-3 model is currently 4097 tokens. However, the current implementation is a  hard stop once the current conversation reaches this limit, which IMO leads to poor user experience. From some quick reading it appears in many instances, as opposed to a hard stop, a strategy of incorporating (n) number of prior conversation elements into subsequent calls is a better approach. This would allow the conversation to continue seamlessly, without the hard stop. Certainly historical conversation elements would naturally age out and not become part of the current model(prompt) context, but it would allow for a reasonable volume of recency without forcing a hard stop for the user. I believe you could also calculate the proximity to the token limitation to determine how many historical conversation elements to discard from subsequent calls. 

E.G.

Human: Optimize this code: {code}
AI: Output
Human: Ok, refactor code to do XyZ and please explain QrT
AI: Output

As prompt accumulates, removing historical elements from the prompt array in whole is advisable. You can calculate the number of tokens the entire prompt will use relative to the total limit and the determine how many prompt elements are required to be removed from the array in order to comply with the model token limit. 

Incorporating this feature would improve the usability considerably of CodeGPT. Additionally, this is already effectively the result, as conversations are useless once they accumulate, and the user is required to manually create a new conversation. The conversation itself from an offline perspective can continue in perpetuity for the historical benefit of the user, but the interaction with ChatGPT will only include the allowable history.

Thanks again for your time, in review.

**Comment by carlrobertoh** [comment]
Hi @chriskyndrid 

I like the idea of having seamless conversation despite the token limitation. If I understood you correctly, you're suggesting discarding the earliest historical conversations (or truncating the previous messages) based on the new prompt token count?

If that's the case, then I see two issues:

- Technical difficulties - since the response is being streamed, we're [unable to retrieve the usage info](https://community.openai.com/t/usage-info-in-api-responses/18862/12) from the response. Another option would be to calculate the total ourselves by using an existing library, but unfortunately, I couldn't find any written in Java. A workaround would be to use the [tiktoken](https://github.com/openai/tiktoken) library, but that requires mixing Java with python...
- High quota - every request we make will cost you around 4k tokens. For example, even a simple "Hi" prompt will cost 0.008 USD (gpt-3.5). However, I guess we can reduce the token limit to e.g. 1k and work around that.

Thank you for the feature request!

**Comment by chriskyndrid** [comment]
@carlrobertoh thanks for getting back to me. Here are my thoughts:

1) Would [jtokkit](https://github.com/knuddelsgmbh/jtokkit) work?  I belive GPT 3.5 uses cl100k_base. Otherwise approximation could be a strategy, though that would get complicated based on language.

2) From a cost perspective, I'm personally not very concerned about that. A compromise would be create a check box in the setup that allows for perpetual conversations with a caveat on token utilization. You could default it to off(same functionality as today) and allow the user to decide. Generally speak, for simple tasks like optimizations, etc, the impact will likely be minimal if non existent with this change. If the user decides to continue an ongoing conversation, you could argue even in the current situation(how you have it currently), they are accepting the costs as the historical prompt elements are already stacking and then hard terminate, often in the middle of a dialog. Going a step further, you could, although I don't think it is particularly necessary, allow the user to specify the maximum number of tokens they're willing to afford. I would not however, arbitrarily reduce the number of tokens allowed to save cost(like your suggestion to limit at 1k), as you loose the benefit of context. If it's a concern, a combination of allowing the user to toggle the feature and specify maximum token limits would be adequate. 

3) As far as strategy for removing historical conversation elements. I haven't reviewed your code....but assuming the prior conversation elements are stored in an array(or could be), I would calculate the number of tokens that need to be removed given the new incoming prompt and then determine the number of prompt elements to remove starting with the oldest prompt. This could require more thought, but I think truncated elements from the oldest prompt to fit the incoming prompt could cause contextual issues...but maybe not.

**Comment by carlrobertoh** [comment]
1. `jtokkit` is a great find, I believe that could do the trick. Approximation can't be used since most of the people are Chinese.

2. I think adding a check box to a settings panel is bit hard to find(or not), I would rather trigger a warning alert once the token limit exceeds and let the users decide whether they want to continue the ongoing conversation or not. I agree with your suggestion as to custom limits. This could be part of a generic request params overriding logic and I would leave that out for now.

3. Truncating the messages is probably a bad idea yes, most likely we need to discard the entire message/messages to fit the prompt. The logic probably needs to be built inside the [CompletionRequestProvider](https://github.com/carlrobertoh/CodeGPT/blob/master/src/main/java/ee/carlrobert/codegpt/client/CompletionRequestProvider.java) that is responsible of creating the API request payload or maybe even in the [client library](https://github.com/carlrobertoh/openai-client) itself...

**Comment by carlrobertoh** [comment]
FYI: The `jtokkit` seems to be working really good and I'm thinking of adding the token counter to the toolbar:

<img width="405" alt="Screen Shot 2023-03-30 at 23 43 43" src="https://user-images.githubusercontent.com/15891408/228981543-70781273-c277-44a9-a4d3-58232372a42d.png">

Not yet sure if I'm going to include it in the next release or not.

**Comment by chriskyndrid** [comment]
@carlrobertoh,

That looks good. You might consider doing something different than raising an alert when the user hits the token limit and begins the perpetual "high" token transmission(maximal cost), something like changing the Tokens: XX/XXX to red or something. 

That's a bit shameless on my part, but it would be a PITA to have a popup raised whenever I hit the point where each transmission represents close to token limit, as for me, it will regularly occur. 

Otherwise, thanks for your efforts on this.

**Comment by carlrobertoh** [comment]
@chriskyndrid 

Having a colorful indicator sounds like a really good idea!

Regarding to the popup, I think this can be easily solved by adding the "Don't ask me again" option inside the dialog or smth.

Also, I'm not sure when I am going to start with the implementation since there are few other requested features in my current bucketlist.

**Comment by carlrobertoh** [comment]
@chriskyndrid Support for seamless conversations has been added in version 1.10.2. However, it is currently only available for the main models **gpt-3.5** and **gpt-4**. I will add the support for other models in the near future.

**Comment by BenceSzalai** [comment]
> FYI: The `jtokkit` seems to be working really good and I'm thinking of adding the token counter to the toolbar:
> 
> <img alt="Screen Shot 2023-03-30 at 23 43 43" width="405" src="https://user-images.githubusercontent.com/15891408/228981543-70781273-c277-44a9-a4d3-58232372a42d.png">
> 
> Not yet sure if I'm going to include it in the next release or not.

Please include it. It looks super useful.
