### ISSUE TITLE
Number of tokens allowed for clause sonnet is too low

### ISSUE THREAD

**Issue by twidi** [carlrobertoh/CodeGPT#712]
### What happened?

I added some files in the chat to use with claude 3.5 sonnet and I receive this message:

"The total number of tokens requested 53034 exceeds the maximum limit of 24576 for model claude-3.5-sonnet. Try breaking your request into smaller chunks or summarizing your input."

Sonnet allowing 200k tokens I'm not sure what is wrong or if it's a bug in CodeGPT

When searching online for "24576 tokens" it's seem to be related with llama but here I use Clade 3.5 Sonnet via my CodeGPT account

### Relevant log output or stack trace

```shell
The total number of tokens requested 53034 exceeds the maximum limit of 24576 for model claude-3.5-sonnet. Try breaking your request into smaller chunks or summarizing your input.
```

### Steps to reproduce

Add enough files in the chat so that the total number of tokens exceed this value 

### CodeGPT version

2.11.3-241.1

### Operating System

Linux

**Comment by carlrobertoh** [comment]
Since version 2.11.5, I have introduced a RAG for the included files in the session and I have increased the limits to 200k. Unfortunately, at $10 per month, I simply cannot afford higher limits, so this seemed like the best alternative.

I will provide more information about this soon.

**Comment by evrenesat** [comment]
@carlrobertoh have you found time to explain how this works? I really wonder how it behaves in both Pro CodeGPT backend and others backends:
- If I add to many files, does it silently ignore some or give an error. Or it pass everything within limits of the target model until I reach my monthly token qouta?
- How that 6m token limitation works for using Sonnet 3.5 vs Qwen 32b?
- If we don't explicitly add any files, does it try to do anything smart to provide a limited context?
- Is that RAG treatment special to CodeGPT backend?

**Comment by carlrobertoh** [comment]
Hey @evrenesat,

The current individual plan has request limits per model in place. The top-tier models (Sonnet 3.5 and GPT-4o) have a maximum input limit of 24k tokens, while the smaller models can handle up to 32k tokens. However, keep in mind that these limits only apply to your chat session without any other context referenced.

When it comes to referencing files, the system silently compresses the attached context to 16k tokens using RAG, which will be passed along with your original prompt. Additionally, I will soon implement a similar approach to regular chat sessions as well, to keep the conversation flow smooth while saving costs on my end.

I understand the importance of this information, and I will make sure to make it more accessible and visible in the near future.

**Comment by evrenesat** [comment]
> However, keep in mind that these limits only apply to your chat session without any other context referenced.
> When it comes to referencing files, the system silently compresses the attached context to 16k tokens using RAG

Thanks for the explanation. Is that means, for Sonnet, our limit on the chatbox token counter is 40K? What happens when we reach it?

Btw; When I tried 10k+ context size question with o1-mini, I got an ugly IDE error stating I exceed the token limit. IMHO, these errors should be shown in the chatbox or something like that. It would be even better if client could get the limits on IDE startup (if they can't be hardcoded), and warn us while we are trying to add files to context.  

As a related improvement, when the conversation has more than one message/response pairs, it would be nice to be able to put a context break after each message, just like the "context shield" feature of msty.app.
<img width="400" alt="image" src="https://github.com/user-attachments/assets/8a1af563-d238-4c56-8d0b-3a2677a5490c" />

**Comment by carlrobertoh** [comment]
@evrenesat 

> Thanks for the explanation. Is that means, for Sonnet, our limit on the chatbox token counter is (24+16)K? What happens when we reach that?

The 24k limit applies only to the current chat session messages. For example, when you reference files that exceed the limit, the back-end will compress those files to 16k tokens, which then will be appended to the final conversation. However, I believe the current logic allows you to continue if the messages contain e.g. 22k tokens, and you pass in another 32k via files (this shouldn't be allowed in theory).

> Btw; When I tried 10k+ context size question with o1-mini, I got an ugly IDE error stating I exceed the token limit. IMHO, these errors should be shown in the chatbox or something like that. It would be even better if client could get the limits on IDE startup (if they can't be hardcoded), and warn us while we are trying to add files to context.

Thanks for reporting this! The `o1-mini` indeed has a lower limit than the rest. I will make sure to increase it to 24k by early next week. Additionally, having this information available within the IDE is a great idea!

> As a related improvement, when the conversation has more than one message/response pairs, it would be nice to be able to put a context break after each message, just like the "context shield" feature of msty.app.

Actually, in the early phase, we had something similar in place and it should still exist today for models with configured context limits. For example, if you use the OpenAI provider directly and the context exceeds e.g. 128k tokens, CodeGPT will start throwing out earlier messages to fit within that limit.

This is a good idea for non-paying users who are not using the CodeGPT API directly. However, for our use case, I want to apply similar logic to what I have done for files compression. Instead of discarding earlier messages and losing context, I want to apply RAG over the input messages and preserve the most relevant information related to your last question. 

I believe Cursor is doing something similar, i.e. the input context never exceeds over 10k tokens.
