### ISSUE TITLE
CodeGPT plugin repeatedly prompts for API key after updates

### ISSUE THREAD

**Issue by nuth-vireak** [carlrobertoh/CodeGPT#82]
Hello, I keep having the same problem with the CodeGPT plugin in IntelliJ IDE, PhpStorm... 
Every time I update the plugin, it asks me to enter the API key again, even though I've already entered it before.

 Can you help fix this issue? Thanks.

**Comment by carlrobertoh** [comment]
Hi

If you updated the plugin from version earlier than 1.7.0 then this might happen.

Since the plugin is still in an early phase, I’m changing some of the settings regularly and creating new state instances to prevent any deserialization errors happening. Hopefully soon, the plugin updates will be more stable.

Sorry for the inconveniences
