### ISSUE TITLE
Add conversation tabs

### ISSUE THREAD

**Issue by Ryan-Knowles** [carlrobertoh/CodeGPT#9]
Feature Request:

Add conversation tabs with the UI so we can have multiple different conversations in progress at the same time similar to the web ChatGPT interface.

Recommendation: This might seem weird in the current context of how the plugin works. I think if you can group a question-response pair as a single entity then we can click an entity and send it to a folder/conversation/container so we can keep these things organized and in one place as we build up a Q/A history.

**Comment by carlrobertoh** [comment]
Hi @Ryan-Knowles  

This is something I have been thinking of some time now but in order to achieve this, I need to improve the session management first. One way to handle it, is to hold the previous sessions/conversations inside a state object(similarly how the settings are stored/preserved).

This is definitely in my bucket list and will implement it as soon as I find some time.

Best regards

**Comment by mustafacakirogluK24** [comment]
I'd love to retain previous sessions/conversations because I usually work on big features that takes days and as soon as I close the AS, I lose all my previous conversations. This is the only reason why I still use the web version. If you can add both conversation tabs & conversation history I think I'll completely abandon the website. Thanks for considering this!

**Comment by carlrobertoh** [comment]
The feature is in development and I will try to deliver the 1st phase by the end of the week.

Best regards

**Comment by qlaall** [comment]
Today I found that all the conversations I had on https://chat.openai.com/chat are gone, 

so it would be great if this plugin can help me keep historical conversations and group them, and it would be great to export the text so that I can Text search of historical sessions in vscode

**Comment by carlrobertoh** [comment]
Support for the conversation history was added in 1.4.0 release.

Missing functionality:
- History export
- Ability to delete existing conversation
- Ability to change the conversation title

Also in which format would you like to download the conversations? 
I was thinking of JSON and perhaps Markdown(easy to read in IDE).

Please report me if you encounter any issues.

Best regards

**Comment by qlaall** [comment]
The reason why I want to export the historical conversation is that I want to be able to input a keyword, just like "Find in Files" in IDEA, and quickly find and browse the context. Therefore, exporting this feature is not the requirement itself, but "Find in Files" is.

**Comment by carlrobertoh** [comment]
Right, that sounds like a great thing to have.
I'll think about it and see what I can do, most likely the conversations need to be stored somewhere in the project path.

**Comment by qlaall** [comment]
I found another scenario: I asked chatGPT how a feature works, and it returned two screens of code, hard to view in the small window of codeGPT, I might want to read the code in a more convenient place to view the code

**Comment by carlrobertoh** [comment]
Hi, what do you mean by two screens of code?
I can add a functionality that opens up the conversation in a new screen, in a markdown format.

**Comment by qlaall** [comment]
My point is, my screen is too small, and when ChatGPT returns too much or too long code, I have to turn two pages to read it all. One of the reasons is that CodeGPT's width is relatively narrow, and I can't place the IDE and CodeGPT side by side.

**Comment by carlrobertoh** [comment]
I will add the option to open the conversation in the editor as a markdown format, will that be helpful?
